### ISSUE TITLE
when program exits abnormally, terminal left in bad state

### ISSUE THREAD

**Issue by unwiredben** [voctav/voja4_nibbler#3]
When you get a situation like "stack overflow" or "jump outside of program", the VM exits with a fprintf, but that doesn't shut down the curses system and leaves the terminal in a bad state until you type "reset".

**Comment by voctav** [comment]
Ack. As a workaround you can type `reset<enter>` blindly to recover. I think `exit()` skips the ncurses cleanup, so need to rework the termination paths to exit cleanly. There will be a larger refactor to change control flow to have the UI drive the sim, then it can more easily handle the cleanup and also report errors in the UI instead of to `stderr`.

**Comment by voctav** [comment]
Fixed in fabf2757636a9dc5fef947293aa81ee084a27297.
